"""add crop_image_path to wound_records

Revision ID: 010df09a4c30
Revises: da3f4caaf3e4
Create Date: 2025-07-17 04:47:55.142418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '010df09a4c30'
down_revision = 'da3f4caaf3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wound_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_image_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('wound_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wound_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wound_area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bodypart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('redness', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('swelling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('heat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pain', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('function_loss', sa.Boolean(), nullable=True))
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('area')
        batch_op.drop_column('body_part')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wound_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_part', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('area', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('width', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('height', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('function_loss')
        batch_op.drop_column('pain')
        batch_op.drop_column('heat')
        batch_op.drop_column('swelling')
        batch_op.drop_column('redness')
        batch_op.drop_column('bodypart')
        batch_op.drop_column('wound_area')
        batch_op.drop_column('wound_height')
        batch_op.drop_column('wound_width')
        batch_op.drop_column('crop_image_path')

    # ### end Alembic commands ###
