"""Add symptom_analysis, recovery_period, care_guide columns

Revision ID: 8b93885f24cb
Revises: 010df09a4c30
Create Date: 2025-07-17 07:03:07.278955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b93885f24cb'
down_revision = '010df09a4c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wound_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptom_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recovery_period', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('care_guide', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wound_records', schema=None) as batch_op:
        batch_op.drop_column('care_guide')
        batch_op.drop_column('recovery_period')
        batch_op.drop_column('symptom_analysis')

    # ### end Alembic commands ###
