"""Add cause column to wound_records

Revision ID: da3f4caaf3e4
Revises: f8fbf5f83e48
Create Date: 2025-07-16 15:02:30.062770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3f4caaf3e4'
down_revision = 'f8fbf5f83e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wound_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('body_part', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wound_records', schema=None) as batch_op:
        batch_op.drop_column('body_part')
        batch_op.drop_column('cause')

    # ### end Alembic commands ###
